# Generated by Django 5.1.7 on 2025-04-11 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main_categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('categories_name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='img/main_categories_img/')),
            ],
            options={
                'db_table': 'main_categories',
            },
        ),
        migrations.CreateModel(
            name='sub_categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sub_categories_name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='img/sub_categories_img/')),
                ('main_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quick_Trade_Client.main_categories')),
            ],
            options={
                'db_table': 'sub_categories',
            },
        ),
    ]
