# Generated by Django 5.1.7 on 2025-04-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quick_Trade_Client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_categories',
            name='image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sub_categories',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
