# Generated by Django 5.1.7 on 2025-04-14 21:08

import Quick_Trade_Client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quick_Trade_Client', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ad_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending'), ('Expired', 'Expired'), ('Rejected', 'Rejected')], default='Active', max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateTimeField(default=Quick_Trade_Client.models.get_30_days_later),
        ),
    ]
