# Generated by Django 5.1.7 on 2025-04-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quick_Trade_Client', '0005_product_ad_status_product_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ad_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending'), ('Expired', 'Expired'), ('Rejected', 'Rejected')], default='Pending', max_length=64),
        ),
    ]
