# Generated by Django 5.1.7 on 2025-04-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quick_Trade_Client', '0006_alter_product_ad_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='media/default/default.png', upload_to='media/listing_images/'),
        ),
    ]
