# Generated by Django 5.1.7 on 2025-04-15 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quick_Trade_Client', '0007_remove_product_image_url_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='main_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Quick_Trade_Client.main_categories'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='sub_categories',
        ),
    ]
